# Generated by Django 4.1.3 on 2022-11-09 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titulo', max_length=100, verbose_name='Titulo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del usuario', verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de edición del usuario', verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'db_table': 'apps_registro',
                'ordering': ['order', 'id', 'title'],
            },
        ),
    ]
