# Generated by Django 4.1.3 on 2022-11-09 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de cración'),
        ),
        migrations.AlterField(
            model_name='registromodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='registromodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
