# Generated by Django 4.1.3 on 2022-11-09 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=40, verbose_name='Nombres')),
                ('last_name', models.CharField(default='', max_length=40, verbose_name='Apellidos')),
                ('full_name', models.CharField(default='', max_length=100, verbose_name='Nombre(s) y Apellido(s)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('fecha_nacimiento', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Fecha de nacimiento del usuario', null=True, verbose_name='Fecha de nacimiento')),
                ('age', models.CharField(default=0, help_text='Edad del usuario', max_length=4, verbose_name='Edad')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'app_client',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PublisherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=40, verbose_name='Nombres')),
                ('last_name', models.CharField(default='', max_length=40, verbose_name='Apellidos')),
                ('full_name', models.CharField(default='', max_length=100, verbose_name='Nombre(s) y Apellido(s)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('fecha_nacimiento', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Fecha de nacimiento del usuario', null=True, verbose_name='Fecha de nacimiento')),
                ('age', models.CharField(default=0, help_text='Edad del usuario', max_length=4, verbose_name='Edad')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Editor',
                'verbose_name_plural': 'Editores',
                'db_table': 'app_publisher',
                'ordering': ['order'],
            },
        ),
    ]
