# Generated by Django 4.1.3 on 2022-11-09 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='publishermodel',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='birthday',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='publishermodel',
            name='birthday',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='age',
            field=models.CharField(default=0, max_length=4, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='publishermodel',
            name='age',
            field=models.CharField(default=0, max_length=4, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='publishermodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Orden'),
        ),
    ]
