# Generated by Django 4.1.3 on 2022-11-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0003_alter_categoriesobjectmodel_order'),
        ('usuarios', '0002_remove_clientmodel_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientModel',
            new_name='ClientsModel',
        ),
        migrations.RenameModel(
            old_name='PublisherModel',
            new_name='PublishersModel',
        ),
    ]
