# Generated by Django 4.1.3 on 2022-11-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_clientmodel_clientsmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishersmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
