# Generated by Django 4.1.3 on 2022-11-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_clientsmodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsmodel',
            name='age',
            field=models.IntegerField(default=0, max_length=4, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='publishersmodel',
            name='age',
            field=models.IntegerField(default=0, max_length=4, verbose_name='Edad'),
        ),
    ]
