# Generated by Django 4.1.3 on 2022-11-09 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesObjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50, verbose_name='Categoria')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'app_category_object',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ObjetoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100, verbose_name='Nombre del objeto')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('object_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.categoriesobjectmodel')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.publishermodel')),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
                'db_table': 'app_object',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UseObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(verbose_name='Disponibilidad')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.objetomodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.clientmodel')),
            ],
            options={
                'verbose_name': 'Uso de objeto',
                'verbose_name_plural': 'Uso de objetos',
                'db_table': 'app_use_object',
                'ordering': ['order'],
            },
        ),
    ]
