# Generated by Django 4.1.3 on 2022-11-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObjetoModel',
            new_name='ObjetcModel',
        ),
    ]
