# Generated by Django 4.1.3 on 2022-11-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0002_rename_objetomodel_objetcmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesobjectmodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Orden'),
        ),
    ]
