# Generated by Django 4.1.3 on 2022-11-10 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0004_alter_objetcmodel_order_alter_useobject_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesobjectmodel',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de cración'),
        ),
    ]
