# Generated by Django 4.1.3 on 2022-11-10 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0006_alter_objetcmodel_object_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_use', to='objetos.objetcmodel'),
        ),
    ]
