# Generated by Django 4.1.3 on 2022-11-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_clientsmodel_created_and_more'),
        ('objetos', '0007_alter_useobject_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseObject',
            new_name='UseObjectModel',
        ),
    ]
